name: Upstream Sync

on:
  schedule:
    - cron: '* 17 * * 3'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Upstream Changes
        run: |
          git remote add upstream https://github.com/tgstation/tgstation
          git fetch upstream master:update
          git checkout update
          git branch --set-upstream-to=upstream/master update
          git checkout -b upstream_pr update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: upstream_pr
          base: master
          title: "Upstream"
          body: "
          🆑 MassMeta
          add: Upstream
          /:cl:"
