name: Upstream Sync

on:
  schedule:
    - cron: '* 17 * * 3'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Upstream Changes
        run: |
          git remote add upstream https://github.com/tgstation/tgstation
          git fetch upstream master
          git checkout master
          git merge upstream/master

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          committer: upstream-o-tron-3000[bot] <179393467+upstream-o-tron-3000[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: upstream
          delete-branch: true
          base: master
          title: "Upstream"
          body: "
          🆑 MassMeta
          add: Upstream
          /:cl:"
